# Generated by Django 5.1.3 on 2024-11-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='image')),
                ('decription', models.CharField(default='2024-01-01', max_length=500)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='trombil3.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='trombil3.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='trombil3.personne')),
            ],
        ),
    ]
