# Generated by Django 5.1.3 on 2024-11-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trombil3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='decription',
        ),
    ]
