# Generated by Django 5.1.3 on 2024-11-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombil3', '0002_remove_personne_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
